- .eslintrc.json
- app.js
- package.json
> Promoting 0.3.1 dev branch to main

- README.md
- app.js
- package.json
Releasing 0.4.1 to `main`. Resolves issue #6.
> Releasing 0.4.1 - see README.md release notes

- README.md
- app.js
- package.json
* Added logging of non-sensitive startup parameters - [issue #15](https://github.com/jlyons210/discord-bot-ol-bootsie/issues/15)
* Added debug logging to pruning function, suspect it may get stuck in a loop - [issue #14](https://github.com/jlyons210/discord-bot-ol-bootsie/issues/14). Issue remains open until cause of hang is identified.
* Added [Table of Contents](#table-of-contents) to `README.md`.
* Bug fixes:
* Improved error handling for empty OpenAI API responses, added trap for 4XX (fatal) and 5XX (retriable) errors - [issue #17](https://github.com/jlyons210/discord-bot-ol-bootsie/issues/17).
> Releasing 0.4.2 - see README.md release notes

- README.md
- app.js
- package.json
Removed unused `DISCORD_GUILD_ID` and `DISCORD_CLIENT_ID` environment variables from `app.js` and `README.md`.
>  Cleaned up unused environment variables (issue #15) - releasing 0.4.3 

- .eslintrc.json
- README.md
- app.js
- lib/lib-discord.js
- lib/lib-openai.js
- package.json
* Refactored code into multiple .js files to better group functionality - [issue #16](https://github.com/jlyons210/discord-bot-ol-bootsie/issues/16):
* Discord-specific functions moved to `lib/lib-discord.js`
* OpenAI-specific functions moved to `lib/lib-openai.js`
* Changed all synchronous functions to `async` with `await` calls to stop blocking the event loop (possibly causing issue #14).
* Updated OpenAI API call retry logic:
* Instead of retrying indefinitely on 5XX errors, `retryRequest (bool)` was changed to `remainingRetryCount` which starts with the `OPENAI_MAX_RETRIES` environment setting.
* The retry loop decrements. Fatal errors (4XX) will immediately decrement the loop to `0` to prevent retry.
* Fixed a big glitch in the `README.md` documentation:
* [Local …
> Happy 0.4.20!!

- README.md
- app.js
- lib/lib-openai.js
- package.json
> #9 - added bot DM support, bump to 0.6.0

- package.json
Forgot to bump package version
> Bumping to 0.7.2

- .eslintrc
- Dockerfile
- README.md
- package.json
- src/app.ts
- src/lib/ConfigTemplate/Config.ts
- src/lib/ConfigTemplate/ConfigTemplate.json
- src/lib/DiscordBot/DiscordBot.ts
- src/lib/DiscordBot/DiscordBotConvoMode.ts
- src/lib/DiscordBot/DiscordBotThreadMode.ts
- src/lib/DiscordBot/HistoryMessage.ts
- src/lib/DiscordBot/IHistoryMessage.ts
- src/lib/DiscordBot/index.ts
- src/lib/Logger/Logger.ts
- src/lib/OpenAI/OpenAI.ts
> Resolving #36, #50, #57

- README.md
- package.json
- src/lib/DiscordBot/DiscordBot.ts
- src/lib/OpenAI/OpenAI.ts
- src/lib/OpenAI/PayloadMessage.ts
> 63 bot crashes if payloadmessagename has invalid characters

- src/lib/OpenAI/PayloadMessage.ts
> Resolving #63 and #64

- README.md
- package.json
- src/lib/DiscordBot/DiscordBot.ts
> Fixing issue #68, bump to 0.10.2

- README.md
- package-lock.json
- package.json
- src/lib/DiscordBot/DiscordBot.ts
- src/lib/DiscordBot/HistoryMessage.ts
- src/lib/DiscordBot/HistoryMessageConfiguration.ts
- src/lib/DiscordBot/index.ts
- src/lib/ExpirableObject/HistoryMessage/HistoryMessage.ts
- src/lib/ExpirableObject/HistoryMessage/HistoryMessageBucket.ts
- src/lib/ExpirableObject/HistoryMessage/HistoryMessageBucketConfiguration.ts
- src/lib/ExpirableObject/HistoryMessage/HistoryMessageConfiguration.ts
- src/lib/ExpirableObject/HistoryMessage/index.ts
- src/lib/OpenAI/CreateImage.ts
> 74 re implement historymessage to use expirableobjectbucket

- src/lib/DiscordBot/DiscordBot.ts
Fixed a bug that made the bot spew nonsense. Message history wasn't making it into the prompt payload.
> Fixing bug in 0.11.3 and re-merging

- README.md
- package-lock.json
- package.json
- src/lib/Config/ConfigTemplate.json
> Resolved #88, bumping to 0.13.0

- README.md
- package.json
- src/lib/Config/Config.ts
- src/lib/Config/ConfigTemplate.json
- src/lib/DiscordBot/DiscordBot.ts
- tests/CreateImage.test.ts
> Resolving #76, bumping to 0.14.0

- src/lib/DiscordBot/DiscordBot.ts
Forgot to remove a debug line with very lengthy output. Stealth updating.
> Resolved #85, bumping to 0.18.0

- doc/changelog.md
- package.json
- src/lib/Config/Config.ts
- src/lib/Config/ConfigTemplate.json
- src/lib/DiscordBot/DiscordBot.ts
- src/lib/OpenAI/CreateChatCompletion/CreateChatCompletion.ts
- src/lib/OpenAI/CreateImage/CreateImage.ts
- src/lib/OpenAI/CreateImage/CreateImageConfiguration.ts
- yarn.lock
> Completed #116, releasing v1.1.0

- src/lib/DiscordBot/DiscordBot.ts
Closes #118 
Add bot version stamp to image embeds
> refactor: Add bot version stamp to image embeds

- doc/changelog.md
- package.json
- src/lib/Config/ConfigTemplate.json
- yarn.lock
Resolves #131 
Resolves #132 
Resolves #133 
Resolves #134
> Testing finished, making some small adjustments

- doc/changelog.md
- package.json
- src/lib/Config/ConfigTemplate.json
- src/lib/DiscordBot/DiscordBot.ts
- src/lib/OpenAI/CreateChatCompletion/CreateChatCompletion.ts
- src/lib/OpenAI/CreateChatCompletion/CreateChatCompletionConfiguration.ts
- src/lib/OpenAI/CreateImage/CreateImage.ts
- src/lib/OpenAI/CreateImage/CreateImageConfiguration.ts
- yarn.lock
> Release 1.3.0

- doc/changelog.md
- package.json
- src/lib/Config/ConfigTemplate.json
- yarn.lock
> Resolving #147
